### ISSUE TITLE
RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by ahustr** [naver-ai/pcme#8] opened 2023-09-20 06:51 UTC
When I load the training set, I get this error in CUBSampler, but I don't know why

**Comment by SanghyukChun** [comment] 2023-09-20 06:58
`StopIteration` is a built-in exception to denote the iteration has been over.
- https://docs.python.org/3/library/exceptions.html#StopIteration
- https://www.w3schools.com/python/gloss_python_iterator_stop.asp

```python
for _epoch in range(n_epochs):
    for data in dataloader:
        # your own code
```

**Comment by ahustr** [comment] 2023-09-20 07:02
thank you, But when I run cub, I get this error and can't train
![image](https://github.com/naver-ai/pcme/assets/55874332/0f24a699-f3f5-4ea4-80e6-f2f91185dede)

**Comment by SanghyukChun** [comment] 2023-09-20 07:04
Could you please attach the full error log?

**Comment by ahustr** [comment] 2023-09-20 07:05
![image](https://github.com/naver-ai/pcme/assets/55874332/e814ed0c-cc80-4024-b2a2-268b27728f63)

**Comment by SanghyukChun** [comment] 2023-09-20 07:05
Wait, why did you run cub.py? Follow this instruction to reproduce CUB results.
https://github.com/naver-ai/pcme#training-with-full-training-classes

**Comment by ahustr** [comment] 2023-09-20 07:08
hh, I was troubleshooting, so I pulled out the code from cub.py![image](https://github.com/naver-ai/pcme/assets/55874332/1e18a598-7091-43b0-94cd-4ab9fa237b3c)

**Comment by ahustr** [comment] 2023-09-20 07:09
![image](https://github.com/naver-ai/pcme/assets/55874332/98ba24ec-0736-4a8e-90ab-5fffb636bd81)

**Comment by SanghyukChun** [comment] 2023-09-20 07:15
It is not an issue of my code.
When you google "generator raised stopiteration", you can easily find the solution.
https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app

I close the issue because it is not a relevant issue to this project.

**Closed as completed by SanghyukChun** 2023-09-20 07:15 UTC

**Comment by ahustr** [comment] 2023-09-20 07:16
Thank you. It should be a problem with python version. Thank you for your work
